//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CSDSERVER\\SQLEXPRESS;Initial Catalog=casree_database;Integrated Secur" +
            "ity=True;Pooling=False")]
        public string casree_databaseConnectionString {
            get {
                return ((string)(this["casree_databaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CSDSERVER\\SQLEXPRESS;Initial Catalog=CASREE_SERVER_DATABASE;Integrate" +
            "d Security=True")]
        public string CASREE_SERVER_DATABASEConnectionString {
            get {
                return ((string)(this["CASREE_SERVER_DATABASEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CSDSERVER\\SQLEXPRESS;Initial Catalog=CASREE_SFTA_DATABASE;Integrated " +
            "Security=True")]
        public string CASREE_SFTA_DATABASEConnectionString {
            get {
                return ((string)(this["CASREE_SFTA_DATABASEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LILUYI-PC\\sqlexpress;Initial Catalog=CASREE_SERVER_DATABASE;Integrate" +
            "d Security=True")]
        public string CASREE_SERVER_DATABASEConnectionString1 {
            get {
                return ((string)(this["CASREE_SERVER_DATABASEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LILUYI-PC\\sqlexpress;Initial Catalog=CASREE_SFTA_DATABASE;Integrated " +
            "Security=True")]
        public string CASREE_SFTA_DATABASEConnectionString1 {
            get {
                return ((string)(this["CASREE_SFTA_DATABASEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUGUOJUN-PC\\SQLEXPRESS;Initial Catalog=CASREE_SERVER_DATABASE;Integra" +
            "ted Security=True")]
        public string CASREE_SERVER_DATABASEConnectionString2 {
            get {
                return ((string)(this["CASREE_SERVER_DATABASEConnectionString2"]));
            }
        }
    }
}
